# mkapp
# ~/pub/go_appengine/dev_appserver.py --high_replication tmp
# ~/pub/go_appengine/appcfg.py update tmp

application: gocircuit-org-app
runtime: go
version: test
api_version: go1

handlers:
- url: /\.appfs.*
  script: _go_app
  secure: always
- url: /admin(/.*)?
  script: _go_app
  login: admin

# MUST BE LAST
- url: /.*
  script: _go_app
